version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: latin_greek_roots_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/var/www/html
      - ./certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
